language: python
python:
  - "3.4"
  - "3.6"  
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - python example.py
  - python -m unittest -v tests.test_api
  - python -m unittest -v tests.test_generate_hmac
  - python -m unittest -v tests.test_make_headers
  - python -m unittest -v tests.test_make_request_bodies
